### ISSUE TITLE
Example outdated

### ISSUE THREAD

**Issue by HugoGresse** [F43nd1r/rhino-android-example#1]
For example, to initialize the Rhino Context, we need to use `RhinoAndroidHelper.prepareContext();` because RhinoAndroidHelper constructor is private now`

**Comment by F43nd1r** [comment]
It's the other way around: prepareContext was the old way, now you should
use the constructor.

Am 09.12.2016 11:41 vorm. schrieb "Hugo Gresse" <notifications@github.com>:

For example, to initialize the Rhino Context, we need to use
RhinoAndroidHelper.prepareContext(); because RhinoAndroidHelper constructor
is private now`

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/F43nd1r/rhino-android-example/issues/1>, or mute the
thread

**Comment by HugoGresse** [comment]
But the constructor is private

**Comment by F43nd1r** [comment]
Which version are you using?

Am 09.12.2016 12:28 nachm. schrieb "Hugo Gresse" <notifications@github.com>:

> But the constructor is private
>

**Comment by HugoGresse** [comment]
Version 1.3, from the README

**Comment by HugoGresse** [comment]
I've created a PR on the lib [here](https://github.com/F43nd1r/rhino-android/pull/2). Closing the issue.
